//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 AppInstaller.rc 使用
//
#pragma once
#define IDR_MANIFEST1                   1
#define IDR_VERSION_ZH_CN               1
#define IDR_VERSION_EN_US               2
#define MANIFEST                        24
#define BLANK_NORMAL                    99
#define BLANK_LIGHT                     100
#define BLANK_PRESS                     101
#define MIN_NORMAL                      102
#define MIN_LIGHT                       103
#define MIN_PRESS                       104
#define MAX_NORMAL                      105
#define MAX_LIGHT                       106
#define MAX_PRESS                       107
#define RESTORE_NORMAL                  108
#define RESTORE_LIGHT                   109
#define RESTORE_PRESS                   110
#define CANCEL_NORMAL                   111
#define CANCEL_LIGHT                    112
#define CANCEL_PRESS                    113
#define BLANK_LARGR_NORMAL              114
#define BLANK_LARGR_LIGHT               115
#define BLANK_LARGR_PRESS               116
#define MIN_LARGR_NORMAL                117
#define MIN_LARGE_LIGHT                 118
#define MIN_LARGR_PRESS                 119
#define MAX_LARGE_NORMAL                120
#define MAX_LARGE_LIGHT                 121
#define MAX_LARGE_PRESS                 122
#define RESTORE_LARGE_NORMAL            123
#define RESTORE_LARGE_LIGHT             124
#define RESTORE_LARGE_PRESS             125
#define CANCEL_LARGE_NORMAL             126
#define CANCEL_LARGE_LIGHT              127
#define CANCEL_LARGE_PRESS              128
#define IDI_MAINICON                    129
#define ICON_TASKBAR                    130
#define ICON_FILE                       131
#define ICON_WHITE                      132
#define ICON_METRO                      133
#define ICON_COLOR                      136
#define WIN_TITLE                       300
#define PAGE_LOADING                    301
#define PAGE_1_TITLE                    302
#define PAGE_INFO_PUBLISHER             303
#define PAGE_INFO_VERSION               304
#define PAGE_FUNCTIONS                  305
#define PAGE_CHECK_RUNWHENREADY         306
#define PAGE_2_LOADCERT                 307
#define PAGE_2_INSTALL                  308
#define PAGE_3_TITLE                    309
#define PAGE_4_TITLE                    310
#define PAGE_5_TITLE                    311
#define DIALOG_SELLET_APPX              312
#define DIALOG_SELLET_UNI               313
#define BUTTON_1_SER1                   314
#define BUTTON_3_SER1                   315
#define BUTTON_4_SER1                   316
#define BUTTON_5_SER1                   317
#define DIALOG_WINTITLE                 318
#define PAGE_1_APPHASINSTALLED          319
#define PAGE_2_TITLE                    320
#define PAGE_1_APP                      321
#define PAGE_2_LOADING                  322
#define PAGE_2_INSTALLING               323
#define CLHELP_1                        330
#define CLHELP_2                        331
#define CLHELP_3                        332
#define CLHELP_4                        333
#define CLHELP_5                        334
#define CLHELP_6                        335
#define CLHELP_7                        336
#define INITWIDTH                       400
#define INITHEIGHT                      401
#define LIMITWIDTH                      402
#define LIMITHEIGHT                     403
#define textSupportCPU                  450
#define textSupportSystem               451
#define textSupportLanguage             452
#define textDependency                  453
#define textDependencyItem              454
#define internetClient                  500
#define internetClientServer            501
#define privateNetworkClientServer      502
#define documentsLibrary                503
#define picturesLibrary                 504
#define videosLibrary                   505
#define musicLibrary                    506
#define enterpriseAuthentication        507
#define sharedUserCertificates          508
#define removableStorage                509
#define appointments                    510
#define contacts                        511
#define phoneCall                       512
#define backgroundMediaPlayback         513
#define pointOfService                  514
#define allJoyn                         515
#define phoneCallHistoryPublic          516
#define microphone                      517
#define offlineMapsManagement           518
#define objects5D                       519
#define objects3D                       519
#define graphicsCaptureWithoutBorder    520
#define bluetooth                       521
#define lowLevelDevices                 522
#define location                        523
#define humaninterfacedevice            524
#define recordedCallsFolder             525
#define proximity                       526
#define webcam                          527
#define graphicsCaptureProgrammatic     528
#define userNotificationListener        529
#define userDataTasks                   530
#define userAccountInformation          531
#define usb                             532
#define systemManagement                533
#define spatialPerception               534
#define smsSend                         535
#define blockedChatMessages             536
#define chat                            537
#define codeGeneration                  538
#define voipCall                        539
#define enterpriseDataPolicy            540
#define inputInjectionBrokered          541
#define remoteSystem                    542
#define inProcessMediaExtension         544
#define webPlatformMediaExtension       545
#define previewStore                    546
#define confirmAppClose                 547
#define runFullTrust                    548
#define previewUiComposition            549
#define slapiQueryLicenseValue          550
#define localSystemServices             551
#define packageManagement               552
#define packageQuery                    553
#define packagePolicySystem             554
#define storeAppInstall                 555
#define appLicensing                    556
#define broadFileSystemAccess           557
#define allowElevation                  558
#define unvirtualizedResources          559
#define extendedExecution               560
#define appointmentsSystem              561
#define contactsSystem                  562
#define phoneCallSystem                 563
#define userDataAccounts                564
#define userDataTasksSystem             565

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
